### PR TITLE
business transaction renamed to transaction

### PR DESCRIPTION
**Pull request by pavolloffay**
@objectiser could you please review. Will merge once this https://github.com/hawkular/hawkular-apm/pull/670 is merged.

### CODE REVIEW

**Comment by objectiser** [comment]
@pavolloffay LGTM - although I'll test once 670 is merged.

**Comment by pavolloffay** [comment]
@objectiser apm#670 is merged, could you please look at this again?

**Comment by objectiser** [comment]
@pavolloffay LGTM :+1: 

As an aside, would it be possible to create a default constructor on the HTTP recorder that uses env variables for URI, username and password?

**Comment by pavolloffay** [comment]
This lib needs to work in browser and also in node.js. In node it is possible to access env variables but in browser I don't think so. 

BTW. `HttpRecorder` has to be instanciated in the APP and if the app is Node.js then developers can do it.

**Pull request merged**
